using System;
using System.Linq;
using System.Linq.Expressions;
using AwesomeAssertions;
using Xunit;

namespace DotNetTesting.ComplexObjectComparison.Templates;

/// <summary>
/// Field exclusion strategies and extension methods
/// Provides reusable exclusion patterns to reduce test code duplication
/// </summary>
public static class ExclusionStrategies
{
    #region Smart Exclusion Extension Methods

    /// <summary>
    /// Exclude common auto-generated fields
    /// Including: IDs, timestamps, version numbers, etc.
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAutoGeneratedFields<T>(this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.EndsWith("Id") &&
                            ctx.SelectedMemberInfo.Name.StartsWith("Generated"))
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            .Excluding(ctx => ctx.Path.Contains("Version"))
            .Excluding(ctx => ctx.Path.Contains("RowVersion"))
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// Exclude audit-related fields
    /// Including: CreatedBy, CreatedAt, ModifiedBy, ModifiedAt
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAuditFields<T>(this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.Contains("CreatedBy"))
            .Excluding(ctx => ctx.Path.Contains("CreatedAt"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedBy"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedAt"))
            .Excluding(ctx => ctx.Path.Contains("UpdatedBy"))
            .Excluding(ctx => ctx.Path.Contains("UpdatedAt"))
            .Excluding(ctx => ctx.Path.Contains("LastModified"));
    }

    /// <summary>
    /// Exclude all datetime-related fields
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAllTimeFields<T>(this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            .Excluding(ctx => ctx.Path.EndsWith("Date"))
            .Excluding(ctx => ctx.Path.Contains("DateTime"))
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// Combined: Exclude all common auto fields
    /// = ExcludingAutoGeneratedFields + ExcludingAuditFields
    /// </summary>
    public static EquivalencyOptions<T> ExcludingCommonAutoFields<T>(this EquivalencyOptions<T> options)
    {
        return options
            .ExcludingAutoGeneratedFields()
            .ExcludingAuditFields();
    }

    /// <summary>
    /// Exclude Entity Framework tracking fields
    /// </summary>
    public static EquivalencyOptions<T> ExcludingEntityFrameworkFields<T>(this EquivalencyOptions<T> options)
    {
        return options
            .ExcludingMissingMembers()              // Exclude EF extra properties
            .Excluding(ctx => ctx.Path.Contains("Navigation"))  // Navigation properties
            .Excluding(ctx => ctx.Path.Contains("Proxy"))       // Proxy properties
            .ExcludingAutoGeneratedFields()
            .ExcludingAuditFields();
    }

    #endregion

    #region Performance Optimization Tools

    /// <summary>
    /// Quick comparison of key properties for large datasets
    /// Avoids deep object traversal, only compares specified key properties
    /// </summary>
    public static void AssertKeyPropertiesOnly<T>(T actual, T expected, params Expression<Func<T, object>>[] keySelectors)
    {
        if (keySelectors == null || keySelectors.Length == 0)
        {
            throw new ArgumentException("Must specify at least one key property", nameof(keySelectors));
        }

        foreach (var selector in keySelectors)
        {
            var actualValue = selector.Compile()(actual);
            var expectedValue = selector.Compile()(expected);

            actualValue.Should().Be(expectedValue,
                $"Key property {GetPropertyName(selector)} should match");
        }
    }

    private static string GetPropertyName<T>(Expression<Func<T, object>> expression)
    {
        return expression.Body switch
        {
            MemberExpression memberExpression => memberExpression.Member.Name,
            UnaryExpression { Operand: MemberExpression unaryMember } => unaryMember.Member.Name,
            _ => expression.ToString()
        };
    }

    #endregion

    #region Conditional Exclusion Extensions

    /// <summary>
    /// Conditionally exclude property based on condition
    /// </summary>
    public static EquivalencyOptions<T> ExcludingWhen<T>(
        this EquivalencyOptions<T> options,
        Expression<Func<T, object>> propertySelector,
        bool condition)
    {
        return condition
            ? options.Excluding(propertySelector)
            : options;
    }

    /// <summary>
    /// Exclude properties with default values
    /// </summary>
    public static EquivalencyOptions<T> ExcludingDefaultValues<T>(this EquivalencyOptions<T> options)
    {
        return options.Excluding(ctx =>
        {
            var value = ctx.SelectedMemberInfo.GetValue(ctx.Subject);
            if (value == null) return false;

            var type = value.GetType();
            var defaultValue = type.IsValueType ? Activator.CreateInstance(type) : null;

            return Equals(value, defaultValue);
        });
    }

    #endregion
}

// Usage examples
public class ExclusionStrategiesExamples
{
    #region Test Models

    public class UserEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int Version { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        public string CreatedBy { get; set; } = string.Empty;
        public string? ModifiedBy { get; set; }
        public DateTime? LastModifiedAt { get; set; }
    }

    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }

        public DateTime CreatedTime { get; set; }
        public DateTime UpdatedTime { get; set; }
        public DateTime? DeletedAt { get; set; }
    }

    #endregion

    #region Example 1: Basic Smart Exclusion

    [Fact]
    public void Example1_UsingSmartExclusion_SimplifiesTest()
    {
        var original = new UserEntity
        {
            Id = 1,
            Name = "John Doe",
            Email = "john@example.com",
            CreatedAt = DateTime.Now.AddDays(-1),
            UpdatedAt = DateTime.Now.AddDays(-1),
            Version = 1,
            CreatedBy = "system"
        };

        var updated = UpdateUser(original);

        updated.Should().BeEquivalentTo(original, options =>
            options.ExcludingCommonAutoFields()
        );
    }

    #endregion

    #region Example 2: Combining Multiple Exclusion Strategies

    [Fact]
    public void Example2_CombineExclusionStrategies_ComplexScenarios()
    {
        var product = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m,
            StockQuantity = 10
        };

        var retrieved = GetProductFromDatabase(product.Id);

        retrieved.Should().BeEquivalentTo(product, options =>
            options.ExcludingAllTimeFields()
                   .ExcludingWhen(p => p.StockQuantity, condition: IsStockVolatile())
        );
    }

    #endregion

    #region Example 3: EF Entity Comparison

    [Fact]
    public void Example3_EFEntityComparison_ExcludeTrackingProperties()
    {
        var expected = new UserEntity
        {
            Id = 1,
            Name = "John Doe",
            Email = "john@example.com"
        };

        var actual = GetUserFromEFContext(1);

        actual.Should().BeEquivalentTo(expected, options =>
            options.ExcludingEntityFrameworkFields()
        );
    }

    #endregion

    #region Example 4: Key Property Quick Comparison

    [Fact]
    public void Example4_KeyPropertyVerification_ImprovesPerformance()
    {
        var expected = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m,
            StockQuantity = 10,
            CreatedTime = DateTime.Now,
            UpdatedTime = DateTime.Now
        };

        var actual = GetProduct(1);

        ExclusionStrategies.AssertKeyPropertiesOnly(
            actual,
            expected,
            p => p.Id,
            p => p.Name,
            p => p.Price,
            p => p.StockQuantity
        );
    }

    #endregion

    #region Example 5: Conditional Exclusion

    [Fact]
    public void Example5_ConditionalExclusion_DynamicDecision()
    {
        var product = new Product { Id = 1, Name = "Laptop", Price = 999 };
        var isIntegrationTest = IsRunningInIntegrationTestEnvironment();

        var actual = GetProduct(1);

        actual.Should().BeEquivalentTo(product, options =>
            options.ExcludingAllTimeFields()
                   .ExcludingWhen(p => p.StockQuantity,
                        condition: isIntegrationTest) // Stock may vary in integration tests
        );
    }

    #endregion

    #region Example 6: Exclude Default Values

    [Fact]
    public void Example6_ExcludeDefaultValues_HandleUninitializedProperties()
    {
        var partialEntity = new UserEntity
        {
            Name = "John Doe",
            Email = "john@example.com"
        };

        var actual = CreateUser(partialEntity);

        actual.Should().BeEquivalentTo(partialEntity, options =>
            options.ExcludingDefaultValues()
                   .ExcludingCommonAutoFields()
        );
    }

    #endregion

    #region Helper Methods

    private UserEntity UpdateUser(UserEntity user)
    {
        user.UpdatedAt = DateTime.Now;
        user.Version++;
        user.ModifiedBy = "admin";
        return user;
    }

    private Product GetProductFromDatabase(int id) => new()
    {
        Id = id,
        Name = "Laptop",
        Price = 999.99m,
        StockQuantity = 10,
        CreatedTime = DateTime.Now,
        UpdatedTime = DateTime.Now
    };

    private UserEntity GetUserFromEFContext(int id) => new()
    {
        Id = id,
        Name = "John Doe",
        Email = "john@example.com",
        CreatedAt = DateTime.Now,
        UpdatedAt = DateTime.Now,
        CreatedBy = "system"
    };

    private Product GetProduct(int id) => GetProductFromDatabase(id);

    private UserEntity CreateUser(UserEntity entity)
    {
        entity.Id = 1;
        entity.Version = 1;
        entity.CreatedAt = DateTime.Now;
        entity.CreatedBy = "system";
        return entity;
    }

    private bool IsStockVolatile() => false;
    private bool IsRunningInIntegrationTestEnvironment() => false;

    #endregion
}
